server:
  port: 8282
  http2:
    enabled: true
resilience4j.circuitbreaker:
  instances:
    getUser:
      registerHealthIndicator: true
      slidingWindowSize: 3
    createUser:
      registerHealthIndicator: true
      slidingWindowSize: 4
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 5s
      failureRateThreshold: 5
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.NullPointerException
      #recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
      #ignoreException

resilience4j.retry:
  instances:
    getUser:
      maxAttempts: 3
      waitDuration: 10s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.NullPointerException
    createUser:
      maxAttempts: 3
      waitDuration: 10s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.NullPointerException

resilience4j.bulkhead:
  instances:
    getUser:
      maxConcurrentCalls: 10
    createUser:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 20

resilience4j.thread-pool-bulkhead:
  instances:
    deleteUser:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1

resilience4j.ratelimiter:
  instances:
    getUser:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
    createUser:
      limitForPeriod: 6
      limitRefreshPeriod: 500ms
      timeoutDuration: 3s

resilience4j.timelimiter:
  instances:
    getUser:
      timeoutDuration: 2s
      cancelRunningFuture: true
    createUser:
      timeoutDuration: 1s
      cancelRunningFuture: false